# Generated by Django 6.0.4 on 2026-04-16 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('columns_json', models.TextField(default='[]')),
                ('protected_attributes_json', models.TextField(default='[]')),
                ('target_column', models.CharField(blank=True, max_length=255, null=True)),
                ('is_analyzed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overall_severity', models.CharField(choices=[('low', 'Low Bias'), ('medium', 'Medium Bias'), ('high', 'High Bias'), ('critical', 'Critical Bias')], default='low', max_length=20)),
                ('overall_score', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True)),
                ('recommendations_json', models.TextField(default='[]')),
                ('detailed_results_json', models.TextField(default='{}')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='FairnessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('demographic_parity', 'Demographic Parity'), ('disparate_impact', 'Disparate Impact'), ('statistical_parity', 'Statistical Parity Difference'), ('equal_opportunity', 'Equal Opportunity'), ('group_size_ratio', 'Group Size Ratio')], max_length=50)),
                ('protected_attribute', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField(default=0.8)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warning', 'Warning'), ('fail', 'Fail')], default='pass', max_length=20)),
                ('details_json', models.TextField(default='{}')),
                ('description', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.analysisresult')),
            ],
            options={
                'ordering': ['protected_attribute', 'metric_type'],
            },
        ),
    ]
